version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: crm_password
      POSTGRES_DB: crm_db
    ports:
      - "5999:5432"
    volumes:
      - postgres_data_crm_final:/var/lib/postgresql/data

volumes:
  postgres_data_crm_final:
